   name: Remote SSH Command
   on: [push]
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Execute SSH Commands
           uses: appleboy/ssh-action@v1.2.0
           with:
             host: ${{ secrets.SSH_HOST }}
             username: ${{ secrets.SSH_USERNAME }}
             key: ${{ secrets.SSH_KEY }}
             port: ${{ secrets.SSH_PORT }}
             script: |
               whoami
               ls -al
               # 其他自定义命令
